version: "3"

services:
  db:
    build:
      context: ./docker/db
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    platform: linux/x86_64
  app:
    build:
      context: ./docker/app
    ports:
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - ./src:/work/backend
    depends_on: ["db"]
  web:
    build:
      context: ./docker/web
    ports:
      - 80:80
    volumes:
      - ./src:/work/backend
    depends_on: ["app"]
